### ISSUE TITLE
后端程序与前端UI怎么共同使用？

### ISSUE THREAD

**Issue by younglifestyle** [archfish/gateway_ui#1]
当使用docker进行部署前后端时，发现无法建立联系，
DEBUG -- : [2ece3b29-66f3-42f5-afb4-19d84d0b627c] Failed to open TCP connection to 127.0.0.1:9092 (Connection refused - connect(2) for "127.0.0.1" port 9092) /usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'

Gateway启动：
docker run -d -p 0.0.0.0:80:80 -p 9093:9093 -p 9092:9092 fagongzi/gateway

Gateway_UI启动：
docker run -d --restart always -p 3000:3000 --name gateway_ui -u 1001:1001 -h
 gateway.ui.production -l SERVICE_80_NAME=gatewayui -e RAILS_ENV=production -e GATEWAY_BACKEND=127.0.0.1:9092 hub.c.163.com/weihailang/gateway_ui

**Comment by archfish** [comment]
Gateway启动容器与UI的容器不同，所以GATEWAY_BACKEND 不能使用回环地址
